/**
 * Single-use, hashed, tenant-bound authorization `state` values.
 *
 * This module is the CSRF control for every authorization-code flow in the
 * product. The invariants it enforces, in order, are:
 *
 * 1. A state value is generated by this process, so an attacker cannot mint one.
 * 2. Only the SHA-256 hash is retained; the raw value exists once, in the
 *    redirect response, and is unrecoverable afterwards.
 * 3. The record is bound to the purpose, IdP, tenant, and return path that the
 *    flow started with, so a state cannot be moved between flows or tenants.
 * 4. A record is consumable exactly once and only inside its short TTL.
 *
 * Consumed records are retained for a bounded grace window rather than deleted
 * immediately, so a replay is reported as a replay instead of an unknown state.
 * A sweep removes everything past the grace window.
 */

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { OAuthFlowError } from "./oauth_error.js";

/** Why a flow was started; a state may not be reused across purposes. */
export type OAuthFlowPurpose = "staff_login" | "calendar_consent";

/** Identity providers this product can authenticate staff against. */
export type StaffIdentityProvider = "supabase" | "google";

/** Default and maximum lifetime of a state record. */
export const DEFAULT_OAUTH_STATE_TTL_SECONDS = 300;
export const MAX_OAUTH_STATE_TTL_SECONDS = 600;
const REPLAY_GRACE_MS = 60_000;
const STATE_ENTROPY_BYTES = 32;
const STATE_PATTERN = /^[A-Za-z0-9_-]{43}$/;
const RETURN_PATH_PATTERN = /^\/[A-Za-z0-9][A-Za-z0-9/_-]{0,127}$/;
const MAX_IN_FLIGHT = 10_000;

/** One pending authorization request; carries the PKCE verifier and nonce. */
export interface OAuthStateRecord {
  /** SHA-256 hex of the raw state; the raw value is never retained. */
  state_hash: string;
  purpose: OAuthFlowPurpose;
  idp: StaffIdentityProvider;
  /** Tenant the flow is bound to, or null for tenant-agnostic staff login. */
  tenant_id: string | null;
  /** Allow-listed relative path the callback returns to. */
  return_path: string;
  code_verifier: string;
  nonce: string;
  issued_at_ms: number;
  expires_at_ms: number;
  consumed_at_ms: number | null;
}

/** Everything needed to start one authorization request. */
export interface IssueOAuthStateInput {
  purpose: OAuthFlowPurpose;
  idp: StaffIdentityProvider;
  tenant_id: string | null;
  return_path: string;
  code_verifier: string;
  nonce: string;
  ttl_seconds?: number;
}

/** The single moment a raw state value is visible to this process. */
export interface IssuedOAuthState {
  state: string;
  expires_at_ms: number;
}

/** Port for state persistence; a multi-instance deployment supplies a shared adapter. */
export interface OAuthStateStore {
  /** Mint and persist one state record, returning the raw value once. */
  issue(input: IssueOAuthStateInput): Promise<IssuedOAuthState>;
  /** Claim one state record, enforcing single use and TTL. */
  consume(raw_state: unknown): Promise<OAuthStateRecord>;
}

/**
 * In-memory state store for a single process.
 *
 * Correct only while one process serves both the authorize and callback
 * requests. A multi-instance deployment must inject a shared adapter; the port
 * exists so that choice stays explicit rather than implicit.
 */
export class InMemoryOAuthStateStore implements OAuthStateStore {
  private readonly records = new Map<string, OAuthStateRecord>();
  private readonly clock: () => number;
  private readonly ttl_ms: number;
  private readonly random: () => Buffer;

  /**
   * Create the store.
   *
   * @param options - Optional clock, entropy source, and TTL override.
   * @throws OAuthFlowError when the TTL is out of bounds.
   */
  constructor(options: { clock?: () => number; ttl_seconds?: number; random?: () => Buffer } = {}) {
    this.clock = options.clock ?? Date.now;
    this.ttl_ms = bounded_ttl_ms(options.ttl_seconds ?? DEFAULT_OAUTH_STATE_TTL_SECONDS);
    this.random = options.random ?? (() => randomBytes(STATE_ENTROPY_BYTES));
    if (typeof this.random !== "function") throw new OAuthFlowError("oauth_configuration_invalid");
  }

  /**
   * Mint one state value and persist only its hash.
   *
   * @param input - Purpose, IdP, tenant, return path, verifier, and nonce.
   * @returns The raw state value, which the caller must place in the redirect.
   * @throws OAuthFlowError when input is malformed or capacity is exhausted.
   */
  async issue(input: IssueOAuthStateInput): Promise<IssuedOAuthState> {
    const minted = this.build_record(input);
    this.sweep(minted.record.issued_at_ms);
    if (this.records.size >= MAX_IN_FLIGHT) throw new OAuthFlowError("oauth_state_capacity");
    this.records.set(minted.record.state_hash, minted.record);
    return { state: minted.state, expires_at_ms: minted.record.expires_at_ms };
  }

  /**
   * Claim one state record exactly once.
   *
   * @param raw_state - Untrusted `state` value from the callback query.
   * @returns The claimed record with its PKCE verifier and nonce.
   * @throws OAuthFlowError for missing, malformed, unknown, expired, or
   * replayed state, and when capacity is exhausted.
   */
  async consume(raw_state: unknown): Promise<OAuthStateRecord> {
    const now = this.clock();
    this.sweep(now);
    if (typeof raw_state !== "string" || raw_state.length === 0) {
      throw new OAuthFlowError("oauth_state_missing");
    }
    if (!STATE_PATTERN.test(raw_state)) throw new OAuthFlowError("oauth_state_malformed");
    const record = this.find(hash_state(raw_state));
    if (record === undefined) throw new OAuthFlowError("oauth_state_unknown");
    if (record.consumed_at_ms !== null) throw new OAuthFlowError("oauth_state_replayed");
    if (now >= record.expires_at_ms) throw new OAuthFlowError("oauth_state_expired");
    const claimed: OAuthStateRecord = { ...record, consumed_at_ms: now };
    this.records.set(claimed.state_hash, claimed);
    return claimed;
  }

  /**
   * Build and validate one pending record.
   *
   * @param input - Untrusted issuance input from a route handler.
   * @returns The record to persist plus the raw state, which is returned to the
   * caller exactly once and never written to storage.
   * @throws OAuthFlowError when any field is malformed.
   */
  private build_record(input: IssueOAuthStateInput): { record: OAuthStateRecord; state: string } {
    const purpose = require_purpose(input?.purpose);
    const idp = require_idp(input?.idp);
    const return_path = require_return_path(input?.return_path);
    if (typeof input?.code_verifier !== "string" || input.code_verifier.length < 43 || input.code_verifier.length > 128) {
      throw new OAuthFlowError("oauth_pkce_invalid");
    }
    if (typeof input.nonce !== "string" || input.nonce.length < 16 || input.nonce.length > 256) {
      throw new OAuthFlowError("oauth_configuration_invalid");
    }
    const issued_at_ms = this.clock();
    const state = this.mint();
    return {
      state,
      record: {
        state_hash: hash_state(state),
        purpose,
        idp,
        tenant_id: input.tenant_id === null || input.tenant_id === undefined ? null : require_tenant_id(input.tenant_id),
        return_path,
        code_verifier: input.code_verifier,
        nonce: input.nonce,
        issued_at_ms,
        expires_at_ms: issued_at_ms + this.ttl_ms,
        consumed_at_ms: null,
      },
    };
  }

  /** Generate one 256-bit state value as unpadded base64url. */
  private mint(): string {
    const entropy = this.random();
    if (!(entropy instanceof Buffer) || entropy.byteLength !== STATE_ENTROPY_BYTES) {
      throw new OAuthFlowError("oauth_configuration_invalid");
    }
    return entropy.toString("base64url");
  }

  /** Look up a hash without leaking which prefix matched through timing. */
  private find(state_hash: string): OAuthStateRecord | undefined {
    const wanted = Buffer.from(state_hash, "hex");
    for (const candidate of this.records.values()) {
      const existing = Buffer.from(candidate.state_hash, "hex");
      if (existing.byteLength === wanted.byteLength && timingSafeEqual(existing, wanted)) return candidate;
    }
    return undefined;
  }

  /** Drop records whose replay grace window has closed. */
  private sweep(now_ms: number): void {
    for (const [key, record] of this.records) {
      if (now_ms - record.expires_at_ms > REPLAY_GRACE_MS) this.records.delete(key);
    }
  }
}

/** SHA-256 hex of a raw state value; the raw value is never stored. */
function hash_state(raw_state: string): string {
  return createHash("sha256").update(raw_state, "utf8").digest("hex");
}

function bounded_ttl_ms(ttl_seconds: number): number {
  if (
    !Number.isSafeInteger(ttl_seconds) ||
    ttl_seconds < 30 ||
    ttl_seconds > MAX_OAUTH_STATE_TTL_SECONDS
  ) {
    throw new OAuthFlowError("oauth_configuration_invalid");
  }
  return ttl_seconds * 1_000;
}

function require_purpose(value: unknown): OAuthFlowPurpose {
  if (value !== "staff_login" && value !== "calendar_consent") {
    throw new OAuthFlowError("oauth_configuration_invalid");
  }
  return value;
}

function require_idp(value: unknown): StaffIdentityProvider {
  if (value !== "supabase" && value !== "google") throw new OAuthFlowError("oauth_idp_unknown");
  return value;
}

function require_tenant_id(value: unknown): string {
  if (typeof value !== "string" || !/^[1-9]\d{0,18}$/.test(value)) {
    throw new OAuthFlowError("oauth_tenant_mismatch");
  }
  return value;
}

function require_return_path(value: unknown): string {
  if (typeof value !== "string" || !RETURN_PATH_PATTERN.test(value)) {
    throw new OAuthFlowError("oauth_return_path_invalid");
  }
  // Re-checked here as well as in `redirect_policy`, because this value is
  // persisted: a shape that navigates somewhere else must never reach storage.
  if (value.includes("//") || value.includes("..") || value.includes("\\") || value.endsWith("/")) {
    throw new OAuthFlowError("oauth_return_path_invalid");
  }
  return value;
}