/**
 * Single-use, hashed, tenant-bound authorization `state` values.
 *
 * This module is the CSRF control for every authorization-code flow in the
 * product. The invariants it enforces, in order, are:
 *
 * 1. A state value is generated by this process, so an attacker cannot mint one.
 * 2. Only the SHA-256 hash is retained; the raw value exists once, in the
 *    redirect response, and is unrecoverable afterwards.
 * 3. The record is bound to the purpose, IdP, tenant, and return path that the
 *    flow started with, so a state cannot be moved between flows or tenants.
 * 4. A record is consumable exactly once and only inside its short TTL.
 *
 * Consumed records are retained for a bounded grace window rather than deleted
 * immediately, so a replay is reported as a replay instead of an unknown state.
 * A sweep removes everything past the grace window.
 *
 * Capacity is bounded and, above the bound, degrading rather than total. An
 * earlier version refused every issuance at the cap, which meant one anonymous
 * caller repeating `GET /auth/login` could fill the table and hold it full for
 * the whole TTL: the store failed closed, but for every user rather than for the
 * flood. The store now evicts the oldest still-unconsumed record to make room,
 * and keeps the refusal for the one case eviction cannot fix (below).
 *
 * Eviction cannot weaken the CSRF control, which is the property that makes
 * dropping a still-valid record acceptable:
 *
 * - An evicted record is *gone*, so its callback fails closed with
 *   `oauth_state_unknown`. No session is created and no token is exchanged, which
 *   is strictly more restrictive than the state having been present.
 * - Absence cannot be turned into a success later, because nothing re-creates the
 *   record: a replayed or evicted value is refused on every subsequent attempt.
 * - Consumed records inside their replay-grace window are never eviction
 *   candidates, so a replay is still reported as a replay rather than
 *   indistinguishable from an unknown value.
 *
 * Legitimate callbacks are protected by admission control in front of the store
 * rather than by eviction order: a bounded per-source rate means a source cannot
 * mint enough records to push a real operator's flow out of the table in the
 * first place.
 *
 * Minting and field validation live in `oauth_state_minter`; this module owns the
 * record shape, the port, and the process-local store.
 */

import { timingSafeEqual } from "node:crypto";
import { OAuthFlowError } from "./oauth_error.js";
import { OAuthStateMinter, hash_state, require_state_value } from "./oauth_state_minter.js";

export {
  DEFAULT_OAUTH_STATE_TTL_SECONDS,
  MAX_OAUTH_STATE_TTL_SECONDS,
  OAuthStateMinter,
  hash_state,
  require_state_value,
} from "./oauth_state_minter.js";

/** Why a flow was started; a state may not be reused across purposes. */
export type OAuthFlowPurpose = "staff_login" | "calendar_consent";

/** Identity providers this product can authenticate staff against. */
export type StaffIdentityProvider = "supabase" | "google";

const REPLAY_GRACE_MS = 60_000;
const MAX_IN_FLIGHT = 10_000;
/**
 * Smallest consumed prefix worth reclaiming from the sweep queue.
 *
 * Compacted only once the cursor is both past this floor and past half the
 * array, so the splice cost is amortized instead of paid on every expiry.
 */
const SWEEP_COMPACT_FLOOR = 1_024;

/** One pending authorization request; carries the PKCE verifier and nonce. */
export interface OAuthStateRecord {
  /** SHA-256 hex of the raw state; the raw value is never retained. */
  state_hash: string;
  purpose: OAuthFlowPurpose;
  idp: StaffIdentityProvider;
  /** Tenant the flow is bound to, or null for tenant-agnostic staff login. */
  tenant_id: string | null;
  /** Allow-listed relative path the callback returns to. */
  return_path: string;
  code_verifier: string;
  nonce: string;
  issued_at_ms: number;
  expires_at_ms: number;
  consumed_at_ms: number | null;
}

/** Everything needed to start one authorization request. */
export interface IssueOAuthStateInput {
  purpose: OAuthFlowPurpose;
  idp: StaffIdentityProvider;
  tenant_id: string | null;
  return_path: string;
  code_verifier: string;
  nonce: string;
  ttl_seconds?: number;
}

/** The single moment a raw state value is visible to this process. */
export interface IssuedOAuthState {
  state: string;
  expires_at_ms: number;
}

/** Port for state persistence; a multi-instance deployment supplies a shared adapter. */
export interface OAuthStateStore {
  /** Mint and persist one state record, returning the raw value once. */
  issue(input: IssueOAuthStateInput): Promise<IssuedOAuthState>;
  /** Claim one state record, enforcing single use and TTL. */
  consume(raw_state: unknown): Promise<OAuthStateRecord>;
}

/**
 * In-memory state store for a single process.
 *
 * Correct only while one process serves both the authorize and callback
 * requests. A multi-instance deployment must inject a shared adapter; the port
 * exists so that choice stays explicit rather than implicit.
 */
export class InMemoryOAuthStateStore implements OAuthStateStore {
  private readonly records = new Map<string, OAuthStateRecord>();
  /**
   * Hashes of retained records that have not been claimed yet, in issuance order.
   *
   * `Set` iteration order is insertion order, so the first live entry is the
   * oldest in-flight flow. Keeping this separate from `records` is what makes
   * eviction an O(1) head scan instead of a full scan of every consumed record.
   */
  private readonly pending = new Set<string>();
  /**
   * Every retained record's hash, in issuance order.
   *
   * All records share one TTL, so this order is also expiry order and the sweep
   * can stop at the first record still inside its grace window. That matters
   * because the sweep runs on every issuance and every claim: a linear scan of
   * all records per request would make the table's own size the cost of the next
   * request, which is the amplification this store exists to bound.
   */
  private readonly order: string[] = [];
  private sweep_cursor = 0;
  private evicted = 0;
  private readonly max_in_flight: number;
  private readonly minter: OAuthStateMinter;
  private readonly clock: () => number;

  /**
   * Create the store.
   *
   * @param options - Optional clock, entropy source, TTL override, and capacity
   * override clamped below the hard bound.
   * @throws OAuthFlowError when the TTL is out of bounds or the capacity is not
   * a whole number in [1, MAX_IN_FLIGHT].
   */
  constructor(options: { clock?: () => number; ttl_seconds?: number; random?: () => Buffer; max_in_flight?: number } = {}) {
    this.clock = options.clock ?? Date.now;
    this.minter = new OAuthStateMinter(options);
    this.max_in_flight = bounded_capacity(options.max_in_flight ?? MAX_IN_FLIGHT);
  }

  /**
   * Mint one state value and persist only its hash.
   *
   * At the capacity bound the oldest unconsumed record is evicted to make room,
   * so a flood degrades into throttling rather than a table that refuses every
   * user until its entries expire. The refusal survives for the case eviction
   * cannot fix: when every retained record is consumed and inside its replay
   * grace window, dropping one would destroy the replay signal, so issuance fails
   * closed instead.
   *
   * @param input - Purpose, IdP, tenant, return path, verifier, and nonce.
   * @returns The raw state value, which the caller must place in the redirect.
   * @throws OAuthFlowError when input is malformed or capacity is exhausted.
   */
  async issue(input: IssueOAuthStateInput): Promise<IssuedOAuthState> {
    const minted = this.minter.build(input);
    this.sweep(minted.record.issued_at_ms);
    if (this.records.size >= this.max_in_flight && !this.evict_oldest_pending()) {
      throw new OAuthFlowError("oauth_state_capacity");
    }
    this.records.set(minted.record.state_hash, minted.record);
    this.pending.add(minted.record.state_hash);
    this.order.push(minted.record.state_hash);
    return { state: minted.state, expires_at_ms: minted.record.expires_at_ms };
  }

  /**
   * Claim one state record exactly once.
   *
   * @param raw_state - Untrusted `state` value from the callback query.
   * @returns The claimed record with its PKCE verifier and nonce.
   * @throws OAuthFlowError for missing, malformed, unknown, expired, or
   * replayed state, and when capacity is exhausted.
   */
  async consume(raw_state: unknown): Promise<OAuthStateRecord> {
    const now = this.clock();
    this.sweep(now);
    const candidate = require_state_value(raw_state);
    const record = this.find(hash_state(candidate));
    if (record === undefined) throw new OAuthFlowError("oauth_state_unknown");
    if (record.consumed_at_ms !== null) throw new OAuthFlowError("oauth_state_replayed");
    if (now >= record.expires_at_ms) throw new OAuthFlowError("oauth_state_expired");
    const claimed: OAuthStateRecord = { ...record, consumed_at_ms: now };
    this.records.set(claimed.state_hash, claimed);
    // Claimed records are no longer eviction candidates: their remaining value is
    // the replay signal, not a slot the store needs.
    this.pending.delete(claimed.state_hash);
    return claimed;
  }

  /**
   * Number of retained records, consumed and in-flight alike.
   *
   * Exposed so the memory bound is assertable rather than assumed.
   *
   * @returns The current record count.
   */
  retained_count(): number {
    return this.records.size;
  }

  /**
   * Number of retained records that have not been claimed.
   *
   * @returns The current in-flight count.
   */
  in_flight_count(): number {
    return this.pending.size;
  }

  /**
   * Number of records dropped to make room since this store was created.
   *
   * @returns The eviction count.
   */
  evicted_count(): number {
    return this.evicted;
  }

  /** Look up a hash without leaking which prefix matched through timing. */
  private find(state_hash: string): OAuthStateRecord | undefined {
    const wanted = Buffer.from(state_hash, "hex");
    for (const candidate of this.records.values()) {
      const existing = Buffer.from(candidate.state_hash, "hex");
      if (existing.byteLength === wanted.byteLength && timingSafeEqual(existing, wanted)) return candidate;
    }
    return undefined;
  }

  /**
   * Drop the oldest retained record that has not been claimed.
   *
   * Consumed records are skipped deliberately: removing one inside its replay
   * grace window would turn a replay into an indistinguishable unknown value and
   * destroy the evidence that the value was already spent.
   *
   * @returns True when a slot was reclaimed; false when every retained record is
   * claimed, in which case the caller must fail closed.
   */
  private evict_oldest_pending(): boolean {
    for (const state_hash of this.pending) {
      if (!this.records.has(state_hash)) {
        this.pending.delete(state_hash);
        continue;
      }
      this.records.delete(state_hash);
      this.pending.delete(state_hash);
      this.evicted += 1;
      return true;
    }
    return false;
  }

  /**
   * Drop records whose replay grace window has closed, oldest first.
   *
   * The cursor makes this amortized: one pass over the expired prefix, then a
   * constant-time check per request until new records push the window forward.
   * `order` is reclaimed once the cursor has consumed enough of it, so the queue
   * itself does not become the leak it exists to prevent.
   */
  private sweep(now_ms: number): void {
    while (this.sweep_cursor < this.order.length) {
      const key = this.order[this.sweep_cursor] as string;
      const record = this.records.get(key);
      if (record !== undefined && now_ms - record.expires_at_ms <= REPLAY_GRACE_MS) return;
      if (record !== undefined) this.records.delete(key);
      this.pending.delete(key);
      this.sweep_cursor += 1;
    }
    this.compact_order();
  }

  /** Drop the consumed prefix of the sweep queue once it dominates the array. */
  private compact_order(): void {
    if (this.sweep_cursor < SWEEP_COMPACT_FLOOR) return;
    if (this.sweep_cursor * 2 < this.order.length) return;
    this.order.splice(0, this.sweep_cursor);
    this.sweep_cursor = 0;
  }
}


/**
 * Clamp a requested capacity to the hard memory bound.
 *
 * A smaller value exists so a test can reach the eviction boundary without minting
 * ten thousand records. It is clamped rather than trusted so no caller, including a
 * misconfigured deployment, can raise the bound above `MAX_IN_FLIGHT`.
 */
function bounded_capacity(max_in_flight: number): number {
  if (!Number.isSafeInteger(max_in_flight) || max_in_flight < 1 || max_in_flight > MAX_IN_FLIGHT) {
    throw new OAuthFlowError("oauth_configuration_invalid");
  }
  return max_in_flight;
}
